# Generated by Django 2.2 on 2021-10-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
