# Generated by Django 2.2 on 2021-10-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20211014_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='docfile',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
